### ISSUE TITLE
V-Inspired logo

### ISSUE THREAD

**Issue by emilyb7** [FAC9/v-inspired#27]
Hi @torikate1, could you please send us the logo? We are having trouble getting it from the website.

It needs to be a fairly high resolution image.

Thanks!

**Comment by Torikate1** [comment]
Hi @emilyb7, sure thing - is this one high res enough? Let me know if not and I'll send something else over.
![vinspired_logo_rgb_purple](https://cloud.githubusercontent.com/assets/25616440/22777798/52273212-eeac-11e6-9310-330860f83cb8.png)

Thanks!

**Comment by emilyb7** [comment]
@Torikate1 thank you! Do you maybe have one in white too? We would like to overlay it on a purple background.

**Comment by Torikate1** [comment]
No problem! Here you go :)

![vinspired_logo_rgb_white](https://cloud.githubusercontent.com/assets/25616440/22779382/830ca604-eeb2-11e6-874b-59f5d8f03d9d.png)
